[package]
name = "futile"
version = "1.0.0"
authors = ["Christo Stephenson <cargo@christo.dev"]
edition = "2018"
license = "MIT"

[dependencies]
diesel = { version = "1.4.4", features = ["postgres"] }
dotenv = "0.15.0"
bcrypt = "0.8.2"